# Generated by Django 5.0.2 on 2024-02-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('agencia', models.CharField(choices=[('AC', 'Águas Claras'), ('AS', 'Asa Sul'), ('GU', 'Guará')], max_length=2)),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
    ]
